// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dilvxpgbkrsnrlwzznxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbHZ4cGdia3JzbnJsd3p6bnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjE3NzgsImV4cCI6MjA2NzQzNzc3OH0.jp5_PX2PS3I64O2QaDZnXpc8PJRA9vMxF7vYZg3yDeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});